version: '2'

services:
  cards-service:
    image: 'vlmaier/cards-service:latest'
    build:
      context: .
    container_name: cards-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'postgres:15.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  minio:
    image: quay.io/minio/minio:latest
    container_name: storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=.F00b4r!
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data:/data

volumes:
  data: